### ISSUE TITLE
UX/UI improvement

### ISSUE THREAD

**Issue by sansyrox** [IOSD/iosd-frontend#15]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request 

**Current behavior:**
The background boxes under "OUR AIM" section on hover are not on same size , i.e. background boxes of events and projects are not in line with the first two

**Expected behavior:**
To make these boxes of equal dimensions

Your operating system
Mac OS

**Would you like to work on the issue?**

Yes , I would like to work on this issue.

**Comment by stealthanthrax** [comment]
<img width="1440" alt="screen shot 2017-10-18 at 10 11 59 pm" src="https://user-images.githubusercontent.com/29942790/31731268-1a6ae3f2-b452-11e7-9d36-6ce78fa0e4c4.png">
@krishnarai30 ,can I work on it?

**Comment by sansyrox** [comment]
@krishnarai30: Can I work on it?

**Comment by stealthanthrax** [comment]
<img width="1440" alt="screen shot 2017-10-18 at 10 11 59 pm" src="https://user-images.githubusercontent.com/29942790/31731305-40bfd8fa-b452-11e7-9d82-84fbe7b7d5d4.png">

**Comment by krishnarai30** [comment]
@stealthanthrax Yes, you may fix this!
