### ISSUE TITLE
Sponsor tree

### ISSUE THREAD

**Issue by krishnarai30** [IOSD/iosd-frontend#20]
Arrange the tree properly all in one lie and not clustered with proper spacing.

**Comment by Prashant047** [comment]
Sir, I am not at home/college, and I don't have my laptop.
Will do when I am back to college

**Comment by krishnarai30** [comment]
@Prashant047 When?

**Comment by Prashant047** [comment]
@krishnarai30 like this??
<img width="1440" alt="screen shot 2017-10-27 at 11 09 22 am" src="https://user-images.githubusercontent.com/19635844/32089383-4f5e2482-bb07-11e7-88a6-886d064f3c0f.png">

**Comment by krishnarai30** [comment]
@Prashant047 nai bhai ek line nai
tree
as in top me badi companies with big logo 
then smaller organization with smaller size logo
sai proportion me sab
and responsive

**Comment by Prashant047** [comment]
Ok I see now
