### ISSUE TITLE
Add Form for Sponsorships from IOSD

### ISSUE THREAD

**Issue by krishnarai30** [IOSD/iosd-frontend#4]
Create a type form before fund your startup section for events to apply for sponsorship from IOSD

Use this form for idea of details required in the form

https://docs.google.com/forms/d/e/1FAIpQLSfINbhWSjZslauz9RPt65ghSW3MA-mGaAhcj2sk3E6f0x5fIQ/viewform

**Comment by ghost** [comment]
form below fund your startups heading?
