### ISSUE TITLE
Change picture in about us from IOSD DTU to IOSD

### ISSUE THREAD

**Issue by krishnarai30** [IOSD/iosd-frontend#5]
Find the new picture in cover photo of IOSD FB PAGE at
https://www.facebook.com/iosdofficial/

**Comment by fareskalaboud** [comment]
[options.zip](https://github.com/IOSD/iosd-frontend/files/1395073/options.zip)

I've added five different options, and I've based the background colour on your logos. 

All background photos are free to use from pexels.com
