### ISSUE TITLE
Update Upcoming Events Section 

### ISSUE THREAD

**Issue by krishnarai30** [IOSD/iosd-frontend#8]
Delete existing data
Add
October Hacktober fest 2017
3 Nov MSI Nidia Game Dev workshop at DTU
Fund YOur Startup December 2017
3 Dec MLH HackDAY Hackathon 
December Winter Training Program

**Comment by fareskalaboud** [comment]
Solved this issue @krishnarai30, see https://github.com/IOSD/iosd-frontend/pull/12

**Comment by krishnarai30** [comment]
Update change 3rd Dec to 2nd December for MLH Local HackDay
